version: '3.7'
services:

  app:
    container_name: app
    build: ./market
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=postgres
    - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  postgres:
    container_name: postgres
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
